services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: magicqc-app
        container_name: magicqc_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: magicqc_nginx
        restart: unless-stopped
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - default
            - robionix_default
        depends_on:
            - app

    db:
        image: mysql:5.7
        container_name: magicqc_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: magicqc_worker
        restart: unless-stopped
        working_dir: /var/www
        command: php artisan queue:work --tries=3 --timeout=90
        volumes:
            - ./:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        depends_on:
            - app
            - db

networks:
    robionix_default:
        external: true

volumes:
    dbdata:
        driver: local
